// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.linkedu.core;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class IAccountService {
    public abstract boolean isLoggedIn();

    public abstract void loginWithPhoneNumber(String number, String password);

    public abstract void signupWithPhoneNumber(String number, String password);

    private static final class CppProxy extends IAccountService
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public boolean isLoggedIn()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isLoggedIn(this.nativeRef);
        }
        private native boolean native_isLoggedIn(long _nativeRef);

        @Override
        public void loginWithPhoneNumber(String number, String password)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_loginWithPhoneNumber(this.nativeRef, number, password);
        }
        private native void native_loginWithPhoneNumber(long _nativeRef, String number, String password);

        @Override
        public void signupWithPhoneNumber(String number, String password)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_signupWithPhoneNumber(this.nativeRef, number, password);
        }
        private native void native_signupWithPhoneNumber(long _nativeRef, String number, String password);
    }
}
