// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from file_storage_provider.djinni

package com.linkedu.core;

public abstract class IFileStorageProvider {
    public abstract String getDocumentPath(String relative);
}
