// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.linkedu.core;

public abstract class ILoginCallback {
    public abstract void onLogin(boolean success);
}
