// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_bundle.djinni

package com.linkedu.core;

public abstract class IPalBundle {
    public abstract IFileStorageProvider getFileStorageProvider();
}
