// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from course.djinni

#include "i_course_service.hpp"  // my header
#include "i_create_course_info.hpp"

namespace djinni_generated {

ICourseService::ICourseService() : ::djinni::JniInterface<::ari::ICourseService, ICourseService>("com/linkedu/core/ICourseService$CppProxy") {}

ICourseService::~ICourseService() = default;


CJNIEXPORT void JNICALL Java_com_linkedu_core_ICourseService_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ari::ICourseService>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_linkedu_core_ICourseService_00024CppProxy_native_1createCourse(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_info)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ari::ICourseService>(nativeRef);
        ref->createCourse(::djinni_generated::ICreateCourseInfo::toCpp(jniEnv, j_info));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
