// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from course.djinni

#pragma once

#include "../../../../../../src/gen/i_course_service.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class ICourseService final : ::djinni::JniInterface<::ari::ICourseService, ICourseService> {
public:
    using CppType = std::shared_ptr<::ari::ICourseService>;
    using CppOptType = std::shared_ptr<::ari::ICourseService>;
    using JniType = jobject;

    using Boxed = ICourseService;

    ~ICourseService();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<ICourseService>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<ICourseService>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    ICourseService();
    friend ::djinni::JniClass<ICourseService>;
    friend ::djinni::JniInterface<::ari::ICourseService, ICourseService>;

};

}  // namespace djinni_generated
