// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from course.djinni

#pragma once

#include "../../../../../../src/gen/i_create_course_info.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class ICreateCourseInfo final : ::djinni::JniInterface<::ari::ICreateCourseInfo, ICreateCourseInfo> {
public:
    using CppType = std::shared_ptr<::ari::ICreateCourseInfo>;
    using CppOptType = std::shared_ptr<::ari::ICreateCourseInfo>;
    using JniType = jobject;

    using Boxed = ICreateCourseInfo;

    ~ICreateCourseInfo();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<ICreateCourseInfo>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<ICreateCourseInfo>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    ICreateCourseInfo();
    friend ::djinni::JniClass<ICreateCourseInfo>;
    friend ::djinni::JniInterface<::ari::ICreateCourseInfo, ICreateCourseInfo>;

};

}  // namespace djinni_generated
