// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from course.djinni

#include "i_create_course_info.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

ICreateCourseInfo::ICreateCourseInfo() : ::djinni::JniInterface<::ari::ICreateCourseInfo, ICreateCourseInfo>("com/linkedu/core/ICreateCourseInfo$CppProxy") {}

ICreateCourseInfo::~ICreateCourseInfo() = default;


CJNIEXPORT void JNICALL Java_com_linkedu_core_ICreateCourseInfo_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ari::ICreateCourseInfo>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_linkedu_core_ICreateCourseInfo_00024CppProxy_native_1setName(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_name)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ari::ICreateCourseInfo>(nativeRef);
        ref->setName(::djinni::String::toCpp(jniEnv, j_name));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_com_linkedu_core_ICreateCourseInfo_00024CppProxy_native_1getName(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ari::ICreateCourseInfo>(nativeRef);
        auto r = ref->getName();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_linkedu_core_ICreateCourseInfo_00024CppProxy_native_1setDescription(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_description)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ari::ICreateCourseInfo>(nativeRef);
        ref->setDescription(::djinni::String::toCpp(jniEnv, j_description));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_com_linkedu_core_ICreateCourseInfo_00024CppProxy_native_1getDescription(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ari::ICreateCourseInfo>(nativeRef);
        auto r = ref->getDescription();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_linkedu_core_ICreateCourseInfo_00024CppProxy_native_1setStartTime(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jlong j_time)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ari::ICreateCourseInfo>(nativeRef);
        ref->setStartTime(::djinni::I64::toCpp(jniEnv, j_time));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jlong JNICALL Java_com_linkedu_core_ICreateCourseInfo_00024CppProxy_native_1getStartTime(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ari::ICreateCourseInfo>(nativeRef);
        auto r = ref->getStartTime();
        return ::djinni::release(::djinni::I64::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_linkedu_core_ICreateCourseInfo_00024CppProxy_native_1setEndTime(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jlong j_time)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ari::ICreateCourseInfo>(nativeRef);
        ref->setEndTime(::djinni::I64::toCpp(jniEnv, j_time));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jlong JNICALL Java_com_linkedu_core_ICreateCourseInfo_00024CppProxy_native_1getEndTime(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ari::ICreateCourseInfo>(nativeRef);
        auto r = ref->getEndTime();
        return ::djinni::release(::djinni::I64::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_linkedu_core_ICreateCourseInfo_newCreateCourseInfo(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ari::ICreateCourseInfo::newCreateCourseInfo();
        return ::djinni::release(::djinni_generated::ICreateCourseInfo::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
