// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from file_storage_provider.djinni

#include "i_file_storage_provider.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

IFileStorageProvider::IFileStorageProvider() : ::djinni::JniInterface<::ari::IFileStorageProvider, IFileStorageProvider>() {}

IFileStorageProvider::~IFileStorageProvider() = default;

IFileStorageProvider::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

IFileStorageProvider::JavaProxy::~JavaProxy() = default;

std::string IFileStorageProvider::JavaProxy::getDocumentPath(const std::string & c_relative) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::IFileStorageProvider>::get();
    auto jret = (jstring)jniEnv->CallObjectMethod(Handle::get().get(), data.method_getDocumentPath,
                                                  ::djinni::get(::djinni::String::fromCpp(jniEnv, c_relative)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::String::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
