// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#include "i_login_callback.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

ILoginCallback::ILoginCallback() : ::djinni::JniInterface<::ari::ILoginCallback, ILoginCallback>() {}

ILoginCallback::~ILoginCallback() = default;

ILoginCallback::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

ILoginCallback::JavaProxy::~JavaProxy() = default;

void ILoginCallback::JavaProxy::onLogin(bool c_success) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::ILoginCallback>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onLogin,
                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c_success)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
