// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include "../../../../../../src/gen/i_login_callback.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class ILoginCallback final : ::djinni::JniInterface<::ari::ILoginCallback, ILoginCallback> {
public:
    using CppType = std::shared_ptr<::ari::ILoginCallback>;
    using CppOptType = std::shared_ptr<::ari::ILoginCallback>;
    using JniType = jobject;

    using Boxed = ILoginCallback;

    ~ILoginCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<ILoginCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<ILoginCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    ILoginCallback();
    friend ::djinni::JniClass<ILoginCallback>;
    friend ::djinni::JniInterface<::ari::ILoginCallback, ILoginCallback>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::ari::ILoginCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onLogin(bool success) override;

    private:
        friend ::djinni::JniInterface<::ari::ILoginCallback, ::djinni_generated::ILoginCallback>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/linkedu/core/ILoginCallback") };
    const jmethodID method_onLogin { ::djinni::jniGetMethodID(clazz.get(), "onLogin", "(Z)V") };
};

}  // namespace djinni_generated
