// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_bundle.djinni

#include "i_pal_bundle.hpp"  // my header
#include "i_file_storage_provider.hpp"

namespace djinni_generated {

IPalBundle::IPalBundle() : ::djinni::JniInterface<::ari::IPalBundle, IPalBundle>() {}

IPalBundle::~IPalBundle() = default;

IPalBundle::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

IPalBundle::JavaProxy::~JavaProxy() = default;

std::shared_ptr<::ari::IFileStorageProvider> IPalBundle::JavaProxy::getFileStorageProvider() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::IPalBundle>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_getFileStorageProvider);
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated::IFileStorageProvider::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
