// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from pal_bundle.djinni

#pragma once

#include "../../../../../../src/gen/pal.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class Pal final : ::djinni::JniInterface<::ari::Pal, Pal> {
public:
    using CppType = std::shared_ptr<::ari::Pal>;
    using CppOptType = std::shared_ptr<::ari::Pal>;
    using JniType = jobject;

    using Boxed = Pal;

    ~Pal();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<Pal>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<Pal>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    Pal();
    friend ::djinni::JniClass<Pal>;
    friend ::djinni::JniInterface<::ari::Pal, Pal>;

};

}  // namespace djinni_generated
