// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from app.djinni

#pragma once

#include "../../../../../../src/gen/service_factory.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class ServiceFactory final : ::djinni::JniInterface<::ari::ServiceFactory, ServiceFactory> {
public:
    using CppType = std::shared_ptr<::ari::ServiceFactory>;
    using CppOptType = std::shared_ptr<::ari::ServiceFactory>;
    using JniType = jobject;

    using Boxed = ServiceFactory;

    ~ServiceFactory();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<ServiceFactory>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<ServiceFactory>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    ServiceFactory();
    friend ::djinni::JniClass<ServiceFactory>;
    friend ::djinni::JniInterface<::ari::ServiceFactory, ServiceFactory>;

};

}  // namespace djinni_generated
