// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from app.djinni

#include "service_factory.hpp"  // my header
#include "i_account_service.hpp"
#include "i_course_service.hpp"

namespace djinni_generated {

ServiceFactory::ServiceFactory() : ::djinni::JniInterface<::ari::ServiceFactory, ServiceFactory>("com/linkedu/core/ServiceFactory$CppProxy") {}

ServiceFactory::~ServiceFactory() = default;


CJNIEXPORT void JNICALL Java_com_linkedu_core_ServiceFactory_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ari::ServiceFactory>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_linkedu_core_ServiceFactory_accountService(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ari::ServiceFactory::accountService();
        return ::djinni::release(::djinni_generated::IAccountService::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_linkedu_core_ServiceFactory_courseService(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ari::ServiceFactory::courseService();
        return ::djinni::release(::djinni_generated::ICourseService::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
