source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

project 'Aristotle/Aristotle.xcodeproj'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

target 'Aristotle' do
    pod 'SnapKit', '~> 4.0.0'
end
